export const APP_NAME = "repoinsight";
export const APP_VERSION = "1.0.4";
export const APP_DESCRIPTION = "Understand any repository in seconds.";

export const DEFAULT_EXCLUDE_PATTERNS = [
  "node_modules/**",
  ".git/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".next/**",
  ".nuxt/**",
  ".cache/**",
  "vendor/**",
  ".venv/**",
  "__pycache__/**",
  "*.min.*",
  "*.bundle.*",
  "*.map",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "*.lock",
  ".gitignore",
];

export const MAX_FILE_SIZE_DEFAULT = 10_485_760;

export const BINARY_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".bmp",
  ".ico",
  ".svg",
  ".webp",
  ".avif",
  ".woff",
  ".woff2",
  ".ttf",
  ".eot",
  ".otf",
  ".pdf",
  ".zip",
  ".tar",
  ".gz",
  ".7z",
  ".rar",
  ".exe",
  ".dll",
  ".so",
  ".dylib",
  ".wasm",
  ".mp3",
  ".mp4",
  ".avi",
  ".mov",
  ".mkv",
  ".webm",
  ".wav",
  ".flac",
  ".ogg",
]);

export const LARGE_ASSET_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".bmp",
  ".ico",
  ".webp",
  ".avif",
  ".woff",
  ".woff2",
  ".ttf",
  ".eot",
  ".otf",
  ".pdf",
  ".mp3",
  ".mp4",
  ".avi",
  ".mov",
  ".mkv",
  ".webm",
]);

export const ENV_FILE_NAMES = new Set([
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
  ".env.staging",
  ".env.test",
]);

export const LANGUAGE_EXTENSIONS: Record<string, string> = {
  ".ts": "TypeScript",
  ".tsx": "TypeScript",
  ".js": "JavaScript",
  ".jsx": "JavaScript",
  ".mjs": "JavaScript",
  ".cjs": "JavaScript",
  ".py": "Python",
  ".rb": "Ruby",
  ".rs": "Rust",
  ".go": "Go",
  ".java": "Java",
  ".kt": "Kotlin",
  ".swift": "Swift",
  ".php": "PHP",
  ".cs": "C#",
  ".fs": "F#",
  ".cpp": "C++",
  ".c": "C",
  ".h": "C/C++ Header",
  ".hpp": "C++ Header",
  ".css": "CSS",
  ".scss": "SCSS",
  ".sass": "SASS",
  ".less": "Less",
  ".html": "HTML",
  ".htm": "HTML",
  ".xml": "XML",
  ".yaml": "YAML",
  ".yml": "YAML",
  ".json": "JSON",
  ".toml": "TOML",
  ".md": "Markdown",
  ".mdx": "MDX",
  ".sql": "SQL",
  ".sh": "Shell",
  ".bash": "Shell",
  ".zsh": "Shell",
  ".ps1": "PowerShell",
  ".dockerfile": "Dockerfile",
  ".zig": "Zig",
  ".ex": "Elixir",
  ".exs": "Elixir",
  ".erl": "Erlang",
  ".hrl": "Erlang",
  ".clj": "Clojure",
  ".cljs": "ClojureScript",
  ".elm": "Elm",
  ".hs": "Haskell",
  ".lua": "Lua",
  ".r": "R",
  ".scala": "Scala",
  ".dart": "Dart",
  ".graphql": "GraphQL",
  ".gql": "GraphQL",
  ".proto": "Protobuf",
  ".svelte": "Svelte",
  ".vue": "Vue",
  ".astro": "Astro",
  ".solid": "Solid",
  ".sol": "Solidity",
  ".nim": "Nim",
  ".crystal": "Crystal",
  ".cr": "Crystal",
  ".raku": "Raku",
  ".pl": "Perl",
  ".pm": "Perl",
  ".tcl": "Tcl",
  ".makefile": "Makefile",
  ".cmake": "CMake",
  ".bat": "Batch",
  ".cmd": "Batch",
};

export const SCORE_WEIGHTS_DEFAULT = {
  documentation: 15,
  testing: 15,
  structure: 12,
  dependencies: 12,
  security: 15,
  maintainability: 12,
  performance: 9,
  codeQuality: 10,
};

export const SCORE_THRESHOLDS = {
  excellent: 90,
  good: 75,
  fair: 60,
  poor: 40,
} as const;

export const INDICATORS = {
  pass: "\u2713",
  warn: "\u26A0",
  fail: "\u2716",
  info: "\u2139",
  star: "\u2605",
  arrow: "\u2192",
};
